config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  resources :customers, only: %i[index create show new]
  get "/signin", to: "login#signin"
  get "/signout", to: "login#signout"
  resources :categories, only: %i[index show]
  resources :products, only: %i[index show]
  resources :carts
  resources :addresses
  resources :checkouts
  resources :orders
  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :province
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories
  validates :name, presence: true
  has_one_attached :image
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :email, uniqueness: true
  validates :first_name, :last_name, :email, :password_digest, presence: true
  has_secure_password
  has_secure_password :recovery_password, validations: false
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  has_many :order_items
  has_many :orders, through: :order_items
  accepts_nested_attributes_for :product_categories, allow_destroy: true
  validates :name, :description, :price, :stock_quantity, presence: true
  validates :stock_quantity, numericality: { message: "must be a number", only_integer: true }
  validates :price, numericality: { message: "must be a number" }
  has_one_attached :image

#   validate :image_format

#   def resize_image
#     return unless image.attached?

#     resized_image = MiniMagick::Image.read(image.download)   # Don't see why this doesn't work?
#     resized_image = resized_image.resize "400 X 400"
#     v_filename = image.filename
#     v_content_type = image.content_type
#     image.purge
#     image.attach(
#       io:           File.open(resized_image.path),
#       filename:     v_filename,
#       content_type: v_content_type
#     )
#   end

#   private
#   def image_format
#     return unless image.attached?
#     if image.blob.content_type.start_with? 'image/'
#     if image.blob.byte_size > 10.megabytes
#       errors.add(:image, 'size needs to be less than 10MB')
#       image.purge
#     else
#       resize_image
#     end
#     else
#       image.purge
#       errors.add(:image, 'needs to be an image')
#     end
#   end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/province.rb
class Province < ApplicationRecord
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    logger.debug(session[:shopping_cart])
    ids = []
    session[:shopping_cart].each_key { |key| ids.append(key) }
    @products = Product.find(ids)
    @items = session[:shopping_cart]
  end

  def create
    session[:shopping_cart][params[:id]] = params[:quantity]
    logger.debug(session[:shopping_cart])
    redirect_to "/cart/"
  end

  def destroy
    logger.debug("Removing #{params[:id]}")
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    logger.debug(session[:shopping_cart])
    ids = []
    session[:shopping_cart].each_key { |key| ids.append(key) }
    @products = Product.find(ids)
    @items = session[:shopping_cart]
  end

  def create
    session[:shopping_cart][params[:id]] = params[:quantity]
    logger.debug(session[:shopping_cart])
    redirect_to carts_path
  end

  def destroy
    logger.debug("Removing #{params[:id]}")
    session[:shopping_cart].delete(params[:id])
    redirect_to carts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<%if @products %>
  <p>Here's what you have in your cart<p>
  <ul>
  <% @products.each do |item| %>
    <li>
      <div class="row">
        <div class="col-md">
          <%= image_tag item.image.variant(resize_to_limit: [100, 100]) %>
          <%= item.name %>
          <%= item.price %>
        </div>
        <div class="col-md">
          <%=
            bootstrap_form_with url: "/cart/update/", method: :patch,
            bootstrap: { layout: "horizontal" } do |form|
          %>
            <%= form.hidden_field :id, value: item.id %>
            <%= form.number_field :quantity, in: 1..item.stock_quantity, value: @items[item.id.to_s], required: true %>
              <%= form.submit "Update"%>
          <% end %>
        <div class="col-md">
          <%=
            bootstrap_form_with url: "/cart/delete/", method: :delete,
            bootstrap: { layout: "horizontal" } do |form|
          %>
            <%= form.hidden_field :id, value: item.id %>
              <%= form.submit "Remove"%>
          <% end %>
        </div>
      </div>
    </li>
    <hr />
  <% end %>
<% else %>
  <p>You don't have anything in your cart yet<p>
<% end %>

app/views/carts/index.html.erb
<%if @products %>
  <p>Here's what you have in your cart<p>
  <ul>
  <% @products.each do |item| %>
    <li>
      <div class="row">
        <div class="col-md">
          <%= image_tag item.image.variant(resize_to_limit: [100, 100]) %>
          <%= item.name %>
          <%= item.price %>
        </div>
        <div class="col-md">
          <%=
            bootstrap_form_with url: carts_url, method: :post,
            bootstrap: { layout: "horizontal" } do |form|
          %>
            <%= form.hidden_field :id, value: item.id %>
            <%= form.number_field :quantity, in: 1..item.stock_quantity, value: @items[item.id.to_s], required: true %>
              <%= form.submit "Update"%>
          <% end %>
        <div class="col-md">
          <%=
            bootstrap_form_with url: cart_path(item.id), method: :delete,
            bootstrap: { layout: "horizontal" } do |form|
          %>
            <%= form.hidden_field :id, value: item.id %>
              <%= form.submit "Remove"%>
          <% end %>
        </div>
      </div>
    </li>
    <hr />
  <% end %>
<% else %>
  <p>You don't have anything in your cart yet<p>
<% end %>
<a href="checkouts">Checkout</a>