config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  resources :customers, only: %i[index create show new]
  get "/signin", to: "login#signin"
  get "/signout", to: "login#signout"
  resources :categories, only: %i[index show]
  resources :products, only: %i[index show]
  resources :carts
  resources :addresses
  resources :checkouts
  resources :orders
  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :province
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories
  validates :name, presence: true
  has_one_attached :image
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :email, uniqueness: true
  validates :first_name, :last_name, :email, :password_digest, presence: true
  has_secure_password
  has_secure_password :recovery_password, validations: false
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  has_many :order_items
  has_many :orders, through: :order_items
  accepts_nested_attributes_for :product_categories, allow_destroy: true
  validates :name, :description, :price, :stock_quantity, presence: true
  validates :stock_quantity, numericality: { message: "must be a number", only_integer: true }
  validates :price, numericality: { message: "must be a number" }
  has_one_attached :image

#   validate :image_format

#   def resize_image
#     return unless image.attached?

#     resized_image = MiniMagick::Image.read(image.download)   # Don't see why this doesn't work?
#     resized_image = resized_image.resize "400 X 400"
#     v_filename = image.filename
#     v_content_type = image.content_type
#     image.purge
#     image.attach(
#       io:           File.open(resized_image.path),
#       filename:     v_filename,
#       content_type: v_content_type
#     )
#   end

#   private
#   def image_format
#     return unless image.attached?
#     if image.blob.content_type.start_with? 'image/'
#     if image.blob.byte_size > 10.megabytes
#       errors.add(:image, 'size needs to be less than 10MB')
#       image.purge
#     else
#       resize_image
#     end
#     else
#       image.purge
#       errors.add(:image, 'needs to be an image')
#     end
#   end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/province.rb
class Province < ApplicationRecord
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    logger.debug(session[:shopping_cart])
    ids = []
    session[:shopping_cart].each_key { |key| ids.append(key) }
    @products = Product.find(ids)
    @items = session[:shopping_cart]
  end

  def create
    session[:shopping_cart][params[:id]] = params[:quantity]
    logger.debug(session[:shopping_cart])
    redirect_to "/cart/"
  end

  def destroy
    logger.debug("Removing #{params[:id]}")
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def index
    if session[:customer_account].nil?
      redirect_to customers_url
    else
      logger.debug(session[:customer_account])
      @addresses = Address.where(customer_id: session[:customer_account]["id"].to_i).joins(:province)
      logger.debug("YOLO YOLO: #{@addresses.nil?}")
      @customer_id = session[:customer_account]["id"]
    end
  end

  def new
    ids = []
    session[:shopping_cart].each_key { |key| ids.append(key) }
    @products = Product.find(ids)
    @items = session[:shopping_cart]
    session[:delivery_address] = params[:id].to_i
    @address = Address.find(params[:id])
  end

  def create
    province = Province.find(session[:delivery_address])
    gst = province.current_GST
    hst = province.current_HST
    pst = province.current_PST

    @order = Order.create(
      PST:         pst,
      GST:         gst,
      HST:         hst,
      customer_id: session[:customer_account]["id"]
    )

    ids = []
    session[:shopping_cart].each_key { |key| ids.append(key) }
    products = Product.find(ids)

    products.each do |p|
      logger.debug(p.id)
      OrderItem.create(
        item_price: p.price,
        quantity:   session[:shopping_cart][p.id.to_s],
        product_id: p.id,
        order_id:   @order.id
      )
    end

    id = @order.id
    @processed_items = OrderItem.where(order_id: id).joins(:product)

    session[:shopping_cart] = {}
    session[:delivery_address] = nil
  end

  def update
    logger.debug("You did it")
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/checkouts/create.html.erb
<h2>Congradulations! Here's what you ordered:</h2>
<ul>
<% sum = 0 %>
<% gst = @order.GST%>
<% hst = @order.HST %>
<% pst = @order.PST %>
<% @processed_items.each do |item| %>
  <li>
    <div class="row">
      <div class="col-md">
        <%= image_tag item.product.image.variant(resize_to_limit: [100, 100]) %>
      </div>
      <div class="col-md">
        <%= item.product.name %>
        price: <%= item.item_price %>
        quantity: <%= item.quantity %>
      </div>
    </div>
  </li>
  <hr />
  <% sum += item.item_price.to_d %>
<% end %>
<h2>GST: <%= gst %></h2>
<h2>HST: <%= hst %></h2>
<h2>PST: <%= pst %></h2>
<h1>Total: $<%= sum * (hst.to_d + gst.to_d + pst.to_d + 1) %></h1>
<h4>You did it Adam, I'm proud of you!</h4>

app/views/checkouts/index.html.erb
<% if @addresses.nil? %>
  <h3>Please enter an address (note: your address will be saved for future deliveries)</h3>
  <%= bootstrap_form_with url: checkout_url, method: :patch, bootstrap: { layout: "horizontal" } do |form| %>
    <%= form.text_field :street, required: true %>
    <%= form.text_field :city, required: true %>
    <%= form.text_field :postal_code, required: true %>
    <%= form.collection_select :province_id, Province.order(:name), :id, :name %>
    <%= form.hidden_field :id, value: @customer_id %>
    <%= form.submit "Add Address" %>
  <% end %>
<% else %>
  <h3>Please select an address</h3>
  <%= bootstrap_form_with url: new_checkout_url, method: :get, bootstrap: { layout: "horizontal" } do |form| %>
    <% @addresses.each do |address| %>
      <% address_label = "#{address.street} #{address.city} #{address.postal_code} #{address.province.name}"%>
        <%= form.radio_button :id, address.id %>
        <%= form.label :id, address_label %>
    <% end %>
    <%= form.submit "Send to Address" %>
  <% end %>
<% end %>

app/views/checkouts/new.html.erb
<h2>Please confirm your order before completing your purchase</h2>
<ul>
<h3>Order</h3>
<% sum = 0 %>
<% gst = @address.province.current_GST %>
<% hst = @address.province.current_HST %>
<% pst = @address.province.current_PST %>
<% @products.each do |item| %>
  <li>
    <div class="row">
      <div class="col-md">
        <%= image_tag item.image.variant(resize_to_limit: [100, 100]) %>
      </div>
      <div class="col-md">
        <%= item.name %>
        price: <%= item.price %>
        quantity: <%= @items[item.id.to_s] %>
      </div>
    </div>
  </li>
  <hr />
  <% sum += item.price.to_d %>
<% end %>
<h2>GST: <%= gst %></h2>
<h2>HST: <%= hst %></h2>
<h2>PST: <%= pst %></h2>
<h1>Total: $<%= sum * (hst.to_d + gst.to_d + pst.to_d + 1) %></h1>
<h3>Shipping Address</h3>
<% address_label = "#{@address.street} #{@address.city} #{@address.postal_code} #{@address.province.name}"%>
  <p><%= address_label %></p>
<hr />
<h4>Click Below to Confrim your Order</h4>
<%= bootstrap_form_with url: checkouts_url, method: :post, bootstrap: { layout: "horizontal" } do |form| %>
  <%= form.submit "Purchase" %>
<% end %>

app/views/checkouts/show.html.erb
<h1>Checkouts#show</h1>
<p>Find me in app/views/checkouts/show.html.erb</p>